name: Retrieve new CABQ Minutes PDFs

on:
  workflow_dispatch: # Allows the workflow to be triggered manually from GitHub UI
  schedule:
    - cron: "0 0 * * *" # every day

env:
  CABQ_MINUTES_DIR: minutes
  CABQ_MINUTES_KEY: ${{ secrets.CABQ_MINUTES_KEY }}

jobs:
  pull-run-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Python Prereqs
        run: pip install -r requirements.txt

      - name: Clone cabq-minutes
        run: |
          bash scripts/pull-minutes.sh

      - name: Fetch Minutes
        run: |
          python __main__.py 10 # retrieve only 10 in this job

      - name: Push cabq-minutes
        run: |
          bash scripts/push-minutes.sh


          
